### ISSUE TITLE
acmg-pathogenicity-classification

### ISSUE THREAD

**Issue by pnrobinson** [HL7/phenomics-exchange-ig#83]
Currently, this has cardinality 1..1, but it is likely many users cannot provide this information. Suggest changing cardinality to 0..1

**Comment by ShahimEssaid** [comment]
This might be referring to the cardinality in [this extension](https://build.fhir.org/ig/HL7/phenomics-exchange-ig/branches/master/StructureDefinition-acmg-pathogenicity-classification.html) but it could also be referring to a previous use in a profile were the cardinality of the .extension slice was 1..1.

There is no current use of this extension in the current IG. Also, if it's about the value's cardinality, it is appropriate to set the value's cardinality to 1..1 since a value is required to use the extension.   Closing
